version: '3.9'

volumes:
  psql: {driver: local}

services:

  database:
    container_name: ormar_casbin_adapter_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:13-alpine
    ports: ['${POSTGRES_PORT}:5432']
    volumes: ['psql:/var/lib/postgresql/data']
